name: Build under Ubuntu

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace
